site_name: Tabademic

theme:
  name: readthedocs
  language: es

nav:
  - Inicio: index.md
  - Primeros pasos: primeros_pasos.md
  - Manipular datos: manipular_datos.md
  - Datos: datos.md
  - Generación de enfrentamientos: generacion_enfrentamientos.md
  - Desarrollador: desarrollador.md